# imports
from dice import Dice
from tkinter import *
from tkinter import ttk

# root
root = Tk()
root.title("Yahtzee")
root.geometry("510x530")
root.resizable(height=0, width=0)

# main_frame
main_frame = ttk.LabelFrame(root, text="Yahtzee", labelanchor=N)
main_frame.grid(rowspan=3, sticky=N, padx=(10, 5), pady=10)
hold_label = ttk.Label(main_frame, text="Hold")
hold_label.grid(padx=10, pady=5)
hold_check1 = ttk.Checkbutton(main_frame)
hold_check1.grid(row=1)
hold_check2 = ttk.Checkbutton(main_frame)
hold_check2.grid(row=2)
hold_check3 = ttk.Checkbutton(main_frame)
hold_check3.grid(row=3)
hold_check4 = ttk.Checkbutton(main_frame)
hold_check4.grid(row=4)
hold_check5 = ttk.Checkbutton(main_frame)
hold_check5.grid(row=5)
dice_label = ttk.Label(main_frame, text="Dice")
dice_label.grid(row=0, column=1)
canvas = Canvas(main_frame, bd=0, highlightthickness=0,
                width=75, height=310, bg="Dark Green")
canvas.grid(row=1, column=1, rowspan=5, padx=10)
roll_button = ttk.Button(main_frame, text="New Round")
roll_button.grid(row=6, columnspan=2, sticky=NSEW, padx=8, pady=(17, 5))
unhold_button = ttk.Button(main_frame, text="Unhold All")
unhold_button.grid(row=7, columnspan=2, sticky=NSEW, padx=8, pady=(5, 5))
roll_label = ttk.Label(main_frame, text="0/3 Rolls", anchor="center")
roll_label.grid(row=8, columnspan=2, padx=8, pady=(5, 5))
round_label = ttk.Label(main_frame, text="1/13 Rounds", anchor="center")
round_label.grid(row=9, columnspan=2, padx=8, pady=(5, 10))

# upper frame
upper_frame = ttk.LabelFrame(root, text="Upper Score", labelanchor=N)
upper_frame.grid(row=0, column=1, sticky=N+E+W, padx=5, pady=(10, 5))
ones_label = ttk.Label(upper_frame, text="Ones:")
ones_label.grid(sticky=W, padx=10, pady=(5, 0))
ones_value_label = ttk.Label(upper_frame, text="0")
ones_value_label.grid(row=0, column=1, sticky=E, padx=10, pady=(5, 0))
twos_label = ttk.Label(upper_frame, text="Twos:")
twos_label.grid(sticky=W, row=1, column=0, padx=10)
twos_value_label = ttk.Label(upper_frame, text="0")
twos_value_label.grid(row=1, column=1, sticky=E, padx=10)
threes_label = ttk.Label(upper_frame, text="Threes:")
threes_label.grid(sticky=W, row=2, column=0, padx=10)
threes_value_label = ttk.Label(upper_frame, text="0")
threes_value_label.grid(row=2, column=1, sticky=E, padx=10)
fours_label = ttk.Label(upper_frame, text="Fours:")
fours_label.grid(sticky=W, row=3, column=0, padx=10)
fours_value_label = ttk.Label(upper_frame, text="0")
fours_value_label.grid(row=3, column=1, sticky=E, padx=10)
fives_label = ttk.Label(upper_frame, text="Fives:")
fives_label.grid(sticky=W, row=4, column=0, padx=10)
fives_value_label = ttk.Label(upper_frame, text="0")
fives_value_label.grid(row=4, column=1, sticky=E, padx=10)
sixes_label = ttk.Label(upper_frame, text="Sixes:")
sixes_label.grid(sticky=W, row=5, column=0, padx=10, pady=(0, 20))
sixes_value_label = ttk.Label(upper_frame, text="0")
sixes_value_label.grid(row=5, column=1, sticky=E, padx=10, pady=(0, 20))
total_label = ttk.Label(upper_frame, text="Total:")
total_label.grid(sticky=W, row=6, column=0, padx=10)
total_value_label = ttk.Label(upper_frame, text="0")
total_value_label.grid(row=6, column=1, sticky=E, padx=10)
bonus_label = ttk.Label(upper_frame, text="Bonus:")
bonus_label.grid(sticky=W, row=7, column=0, padx=10)
bonus_value_label = ttk.Label(upper_frame, text="0")
bonus_value_label.grid(row=7, column=1, sticky=E, padx=10)
upper_total_label = ttk.Label(upper_frame, text="Upper Total:      ")
upper_total_label.grid(sticky=W, row=8, column=0, padx=10, pady=(0, 10))
upper_total_value_label = ttk.Label(upper_frame, text="0")
upper_total_value_label.grid(row=8, column=1, sticky=E, padx=10, pady=(0, 10))

# lower frame
lower_frame = ttk.LabelFrame(root, text="Lower Score", labelanchor=N)
lower_frame.grid(row=1, column=1, rowspan=2, sticky=N, padx=5, pady=(5, 10))
three_of_label = ttk.Label(lower_frame, text="Three of a Kind:")
three_of_label.grid(sticky=W, padx=10, pady=(5, 0))
three_of_label_value = ttk.Label(lower_frame, text="0")
three_of_label_value.grid(row=0, column=1, sticky=E, padx=10, pady=(5, 0))
four_of_label = ttk.Label(lower_frame, text="Four of a Kind:")
four_of_label.grid(sticky=W, row=1, column=0, padx=10)
four_of_value_label = ttk.Label(lower_frame, text="0")
four_of_value_label.grid(row=1, column=1, sticky=E, padx=10)
full_house_label = ttk.Label(lower_frame, text="Full House:")
full_house_label.grid(sticky=W, row=2, column=0, padx=10)
full_house_value_label = ttk.Label(lower_frame, text="0")
full_house_value_label.grid(row=2, column=1, sticky=E, padx=10)
small_straight_label = ttk.Label(lower_frame, text="Small Straight:")
small_straight_label.grid(sticky=W, row=3, column=0, padx=10)
small_straight_value_label = ttk.Label(lower_frame, text="0")
small_straight_value_label.grid(row=3, column=1, sticky=E, padx=10)
large_straight_label = ttk.Label(lower_frame, text="Large Straight:")
large_straight_label.grid(sticky=W, row=4, column=0, padx=10)
large_straight_value_label = ttk.Label(lower_frame, text="0")
large_straight_value_label.grid(row=4, column=1, sticky=E, padx=10)
yahtzee_label = ttk.Label(lower_frame, text="Yahtzee:")
yahtzee_label.grid(sticky=W, row=5, column=0, padx=10)
yahtzee_value_label = ttk.Label(lower_frame, text="0")
yahtzee_value_label.grid(row=5, column=1, sticky=E, padx=10)
chance_label = ttk.Label(lower_frame, text="Chance:")
chance_label.grid(sticky=W, row=6, column=0, padx=10, pady=(0, 20))
chance_value_label = ttk.Label(lower_frame, text="0")
chance_value_label.grid(row=6, column=1, sticky=E, padx=10, pady=(0, 20))
lower_total_label = ttk.Label(lower_frame, text="Lower Total:")
lower_total_label.grid(sticky=W, row=7, column=0, padx=10)
lower_total_value_label = ttk.Label(lower_frame, text="0")
lower_total_value_label.grid(row=7, column=1, sticky=E, padx=10)
yahtzee_bonus_label = ttk.Label(lower_frame, text="Yahtzee Bonus:")
yahtzee_bonus_label.grid(sticky=W, row=8, column=0, padx=10)
yahtzee_bonus_value_label = ttk.Label(lower_frame, text="0")
yahtzee_bonus_value_label.grid(row=8, column=1, sticky=E, padx=10)
combined_total_label = ttk.Label(lower_frame, text="Combined Total:")
combined_total_label.grid(sticky=W, row=9, column=0, padx=10, pady=(0, 10))
combined_total_value_label = ttk.Label(lower_frame, text="0")
combined_total_value_label.grid(
    row=9, column=1, sticky=E, padx=10, pady=(0, 10))

# scoring options frame
option_frame = ttk.LabelFrame(root, text="Scoring Options", labelanchor=N)
option_frame.grid(row=0, column=2, rowspan=2, sticky=N +
                  E+W, padx=(5, 10), pady=(10, 5))
ones_button = ttk.Button(option_frame, text="Ones", width=12)
ones_button.grid(sticky=NSEW, padx=(6, 5), pady=(5, 0))
twos_button = ttk.Button(option_frame, text="Twos", width=12)
twos_button.grid(sticky=NSEW, padx=(6, 5))
threes_button = ttk.Button(option_frame, text="Threes", width=12)
threes_button.grid(sticky=NSEW, padx=(6, 5))
fours_button = ttk.Button(option_frame, text="Fours", width=12)
fours_button.grid(sticky=NSEW, padx=(6, 5))
fives_button = ttk.Button(option_frame, text="Fives", width=12)
fives_button.grid(sticky=NSEW, padx=(6, 5))
sixes_button = ttk.Button(option_frame, text="Sixes", width=12)
sixes_button.grid(sticky=NSEW, padx=(6, 5))
three_of_button = ttk.Button(option_frame, text="Three of a Kind", width=12)
three_of_button.grid(sticky=NSEW, padx=(6, 5))
four_of_button = ttk.Button(option_frame, text="Four of a Kind", width=12)
four_of_button.grid(sticky=NSEW, padx=(6, 5))
full_house_button = ttk.Button(option_frame, text="Full House", width=12)
full_house_button.grid(sticky=NSEW, padx=(6, 5))
small_straight_button = ttk.Button(
    option_frame, text="Small Straight", width=12)
small_straight_button.grid(sticky=NSEW, padx=(6, 5))
large_straight_button = ttk.Button(
    option_frame, text="Large Straight", width=12)
large_straight_button.grid(sticky=NSEW, padx=(6, 5))
yahtzee_button = ttk.Button(option_frame, text="Yahtzee", width=12)
yahtzee_button.grid(sticky=NSEW, padx=(6, 5))
chance_button = ttk.Button(option_frame, text="Chance", width=12)
chance_button.grid(sticky=NSEW, padx=(6, 5), pady=(0, 5))

# grand total label
gtotal_label = ttk.Label(root, text="Grand\nTotal\n0", font=(
    "", "18", "bold"), borderwidth=5, relief="ridge", anchor="center", justify="center", width=12)
gtotal_label.grid(row=2, column=2, sticky=N+E+W, padx=(5, 10), pady=(5, 10))

root.mainloop()
