from tkinter import *
from tkinter import ttk

root = Tk()
root.title("Yahtzee")
root.geometry("1000x1000")

main_frame = ttk.LabelFrame(root, text="Yahtzee", labelanchor=N)
main_frame.grid(rowspan=2, padx=(10,5), pady=10)
#main_frame.grid_propagate(False)
hold_label = ttk.Label(main_frame, text="Hold")
hold_label.grid(padx=10, pady=5)
hold_check1 = ttk.Checkbutton(main_frame)
hold_check1.grid(row=1)
hold_check2 = ttk.Checkbutton(main_frame)
hold_check2.grid(row=2)
hold_check3 = ttk.Checkbutton(main_frame)
hold_check3.grid(row=3)
hold_check4 = ttk.Checkbutton(main_frame)
hold_check4.grid(row=4)
hold_check5 = ttk.Checkbutton(main_frame)
hold_check5.grid(row=5)
dice_label = ttk.Label(main_frame, text = "Dice")
dice_label.grid(row=0, column=1)
canvas = Canvas(main_frame, bd=0, highlightthickness=0, width=75, height=310, bg="Dark Green")
canvas.grid(row=1, column=1, rowspan=5, padx=10)
roll_button = ttk.Button(main_frame, text="New Round")
roll_button.grid(row=6, columnspan=2, sticky=NSEW, padx=8, pady=(10,5))
unhold_button = ttk.Button(main_frame, text="Unhold All")
unhold_button.grid(row=7, columnspan=2, sticky=NSEW, padx=8, pady=(5,5))
roll_label = ttk.Label(main_frame, text = "0/3 Rolls", anchor="center")
roll_label.grid(row=8, columnspan=2, padx=8, pady=(5,5))
round_label = ttk.Label(main_frame, text = "1/13 Rounds", anchor=CENTER)
round_label.grid(row=9, columnspan=2, padx=8, pady=(5,10))

upper_frame = LabelFrame(root, text="Upper Score", labelanchor=N, width=200, height=500)
upper_frame.grid(row=0, column=1, sticky=NSEW, padx=5, pady=(10,5))
upper_frame.grid_propagate(0)
ones_label = Label(upper_frame, text="Ones:")
ones_label.grid(padx=10, pady=(5,0))
#ones_value_label = ttk.Label(upper_frame, text="0")
#ones_value_label.grid(row=0, column=1, sticky=E, padx=10, pady=(5,0))
""" twos_label = ttk.Label(upper_frame, text="Twos:")
twos_label.grid(sticky=W, row=1, column=0, padx=10)
twos_value_label = ttk.Label(upper_frame, text="0")
twos_value_label.grid(row=1, column=1, sticky=E, padx=10)
threes_label = ttk.Label(upper_frame, text="Threes:")
threes_label.grid(sticky=W, row=2, column=0, padx=10)
threes_value_label = ttk.Label(upper_frame, text="0")
threes_value_label.grid(row=2, column=1, sticky=E, padx=10)
fours_label = ttk.Label(upper_frame, text="Fours:")
fours_label.grid(sticky=W, row=3, column=0, padx=10)
fours_value_label = ttk.Label(upper_frame, text="0")
fours_value_label.grid(row=3, column=1, sticky=E, padx=10)
fives_label = ttk.Label(upper_frame, text="Fives:")
fives_label.grid(sticky=W, row=4, column=0, padx=10)
fives_value_label = ttk.Label(upper_frame, text="0")
fives_value_label.grid(row=4, column=1, sticky=E, padx=10)
sixes_label = ttk.Label(upper_frame, text="Sixes:")
sixes_label.grid(sticky=W, row=5, column=0, padx=10, pady=(0,20))
sixes_value_label = ttk.Label(upper_frame, text="0")
sixes_value_label.grid(row=5, column=1, sticky=E, padx=10, pady=(0,20))
total_label = ttk.Label(upper_frame, text="Total:")
total_label.grid(sticky=W, row=6, column=0, padx=10)
total_value_label = ttk.Label(upper_frame, text="0")
total_value_label.grid(row=6, column=1, sticky=E, padx=10)
bonus_label = ttk.Label(upper_frame, text="Bonus:")
bonus_label.grid(sticky=W, row=7, column=0, padx=10)
bonus_value_label = ttk.Label(upper_frame, text="0")
bonus_value_label.grid(row=7, column=1, sticky=E, padx=10)
upper_total_label = ttk.Label(upper_frame, text="Upper Total:")
upper_total_label.grid(sticky=W, row=8, column=0, padx=10, pady=(0,10))
upper_total_value_label = ttk.Label(upper_frame, text="0")
upper_total_value_label.grid(row=8, column=1, sticky=E, padx=10, pady=(0,10)) """

""" lower_frame = ttk.LabelFrame(root, text="Lower Score", labelanchor=N)
lower_frame.grid(row=1, column=1, sticky=N, padx=5, pady=(5,10))
three_of_label = ttk.Label(lower_frame, text="Three of a Kind:")
three_of_label.grid(sticky=W, padx=10, pady=(5,0))
three_of_label_value = ttk.Label(lower_frame, text="0")
three_of_label_value.grid(row=0, column=1, sticky=E, padx=10, pady=(5,0))
four_of_label = ttk.Label(lower_frame, text="Four of a Kind:")
four_of_label.grid(sticky=W, row=1, column=0, padx=10)
four_of_value_label = ttk.Label(lower_frame, text="0")
four_of_value_label.grid(row=1, column=1, sticky=E, padx=10)
full_house_label = ttk.Label(lower_frame, text="Full House:")
full_house_label.grid(sticky=W, row=2, column=0, padx=10)
full_house_value_label = ttk.Label(lower_frame, text="0")
full_house_value_label.grid(row=2, column=1, sticky=E, padx=10)
small_straight_label = ttk.Label(lower_frame, text="Small Straight:")
small_straight_label.grid(sticky=W, row=3, column=0, padx=10)
small_straight_value_label = ttk.Label(lower_frame, text="0")
small_straight_value_label.grid(row=3, column=1, sticky=E, padx=10)
large_straight_label = ttk.Label(lower_frame, text="Large Straight:")
large_straight_label.grid(sticky=W, row=4, column=0, padx=10)
large_straight_value_label = ttk.Label(lower_frame, text="0")
large_straight_value_label.grid(row=4, column=1, sticky=E, padx=10)
yahtzee_label = ttk.Label(lower_frame, text="Yahtzee:")
yahtzee_label.grid(sticky=W, row=5, column=0, padx=10)
yahtzee_value_label = ttk.Label(lower_frame, text="0")
yahtzee_value_label.grid(row=5, column=1, sticky=E, padx=10)
chance_label = ttk.Label(lower_frame, text="Chance:")
chance_label.grid(sticky=W, row=6, column=0, padx=10, pady=(0,20))
chance_value_label = ttk.Label(lower_frame, text="0")
chance_value_label.grid(row=6, column=1, sticky=E, padx=10, pady=(0,20))
lower_total_label = ttk.Label(lower_frame, text="Lower Total:")
lower_total_label.grid(sticky=W, row=7, column=0, padx=10)
lower_total_value_label = ttk.Label(lower_frame, text="0")
lower_total_value_label.grid(row=7, column=1, sticky=E, padx=10)
yahtzee_bonus_label = ttk.Label(lower_frame, text="Yahtzee Bonus:")
yahtzee_bonus_label.grid(sticky=W, row=8, column=0, padx=10)
yahtzee_bonus_value_label = ttk.Label(lower_frame, text="0")
yahtzee_bonus_value_label.grid(row=8, column=1, sticky=E, padx=10)
combined_total_label = ttk.Label(lower_frame, text="Combined Total:")
combined_total_label.grid(sticky=W, row=9, column=0, padx=10, pady=(0,10))
combined_total_value_label = ttk.Label(lower_frame, text="0")
combined_total_value_label.grid(row=9, column=1, sticky=E, padx=10, pady=(0,10)) """

root.mainloop()
